### ISSUE TITLE
Unsupported version requirements. [{:modular_headers=>true}] is not valid..

### ISSUE THREAD

**Issue by blackredscarf** [devansh-ramen/flutter_flurry_analytics#5]
I build the package in ios, but it throws this error.
```
[!] Failed to load 'flurry_analytics' podspec:
[!] Invalid `flurry_analytics.podspec` file: [!] Unsupported version requirements. [{:modular_headers=>true}] is not valid..
```
What is wrong about this ?

**Comment by samng211126** [comment]
You can download this git, then put it in to the project folder
create plugin folder in the project folder
Next ,In pubspec.yaml:
add this
flurry_analytics:
    path: ./plugin/flurry_analytics/

go to this git project folder,
Remove ",:modular_headers => true" in flurry_analytics.podspec

Then follow this link to do some action
https://github.com/ko2ic/image_downloader/issues/9#issuecomment-471608482
,Then you will work it!!!!
